name: CD - Build and push image

on:
  push:
    branches: ["master"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build JAR
        run: mvn -B package -DskipTests

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: milos225/myapp:latest
      - name: Deploy container
        run: |
          docker pull milos225/myapp:latest
          docker stop myapp || true
          docker rm myapp || true
          docker run -d --name myapp -p 8080:8080 milos225/myapp:latest
      - name: Test API
        run: |
          sleep 5
          curl -v http://localhost:8080 || true
